// src/seed.js
// แคตตาล็อกบัตรเครดิตหลักของธนาคารไทย (รวบรวมด้วยมือ — curated)
// ใช้เป็นข้อมูลหลักที่แสดงเสมอ และเป็น fallback เมื่อ scrape ไม่สำเร็จ
//
// *** เงินเดือนขั้นต่ำ/จุดเด่นอ้างอิงเกณฑ์ทั่วไปของแต่ละบัตร (ข้อมูล ณ ปี 2568/2025) ***
// *** เงื่อนไขจริงอาจเปลี่ยนแปลง โปรดตรวจสอบกับธนาคารก่อนสมัครทุกครั้ง ***
// categories = หัวข้อเด่น (ดู id ได้ที่ src/categories.js)

export const SEED = {
  kbank: [
    { title: "บัตรเครดิตแพลทินัม กสิกรไทย", summary: "บัตรหลักสะสมคะแนน K Point ใช้ได้ทุกหมวด ฟรีค่าธรรมเนียมรายปีตามเงื่อนไข", minSalary: 15000, categories: ["lowincome", "points", "nofee"] },
    { title: "บัตรเครดิตไทเทเนียม กสิกรไทย", summary: "บัตรเริ่มต้นสำหรับช้อปปิ้งและใช้จ่ายทั่วไป สะสมคะแนน", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิตกสิกรไทย-ช้อปปี้ (KBank-Shopee)", summary: "เครดิตเงินคืนและคอยน์เมื่อช้อปบน Shopee และใช้จ่ายออนไลน์", minSalary: 15000, categories: ["lowincome", "online", "cashback"] },
    { title: "บัตรเครดิต JOURNEY กสิกรไทย", summary: "สะสมไมล์/คะแนนเพื่อการเดินทาง เหมาะกับสายท่องเที่ยว", minSalary: 15000, categories: ["lowincome", "miles", "travel"] },
    { title: "บัตรเครดิตกสิกรไทย เพื่อผู้ประกอบการ แพลทินัม", summary: "บัตรสำหรับเจ้าของกิจการ เครดิตเงินคืนค่าใช้จ่ายธุรกิจ", minSalary: 50000, categories: ["cashback", "points"] },
    { title: "บัตรเครดิต World Rewards กสิกรไทย", summary: "บัตรระดับบน สิทธิ์เลานจ์สนามบิน ร้านอาหาร ท่องเที่ยว และสะสมคะแนนพิเศษ", minSalary: 50000, categories: ["lounge", "travel", "dining", "points"] },
    { title: "บัตรเครดิต WISDOM กสิกรไทย", summary: "บัตรพรีเมียม สิทธิ์เลานจ์สนามบินและบริการระดับสูง", minSalary: 100000, categories: ["premium", "lounge", "travel", "points"] },
    { title: "บัตรเครดิตเดอะพรีเมียร์ กสิกรไทย", summary: "บัตรสำหรับลูกค้า The Premier สิทธิ์เลานจ์และไลฟ์สไตล์ระดับสูงสุด", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
    { title: "KBank PLUSTINUM", summary: "Miracle Lounge สุวรรณภูมิ (ขาออก ตปท.) 2 ครั้ง/ปี — กดรับ E-Coupon ใน K PLUS ไม่จำกัดสายการบิน", minSalary: 15000, categories: ["lowincome", "lounge", "travel"], url: "https://www.kasikornbank.com/th/personal/creditcard/pages/plustinum.aspx" },
    { title: "KBank JCB Platinum", summary: "Miracle Lounge สุวรรณภูมิ 2 ครั้ง/ปี (ต้องบินการบินไทย) + LoungeKey 8 ประเทศต่างประเทศ", minSalary: 15000, categories: ["lowincome", "lounge", "travel", "points"], url: "https://www.kasikornbank.com/th/personal/creditcard/pages/jcb.aspx" },
  ],
  scb: [
    { title: "บัตรเครดิต SCB VISA Classic", summary: "บัตรเริ่มต้นใช้จ่ายทั่วไป สะสมคะแนน SCB Rewards", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิต SCB Gold", summary: "บัตรทองสำหรับช้อปปิ้งและใช้จ่ายประจำวัน สะสมคะแนน", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิต SCB M VISA (เดอะมอลล์)", summary: "สิทธิ์ช้อปที่เดอะมอลล์/พารากอน สะสม M Point", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิต SCB PLANET", summary: "บัตรสายเที่ยวต่างประเทศและช้อปออนไลน์ อัตราแลกเงินดี", minSalary: 15000, categories: ["lowincome", "travel", "online"] },
    { title: "บัตรเครดิตไทยพาณิชย์ โตโยต้า", summary: "บัตรร่วมโตโยต้า สิทธิ์บริการรถยนต์และเครดิตเงินคืน", minSalary: 15000, categories: ["lowincome", "cashback"] },
    { title: "บัตรเครดิต SCB UP2ME", summary: "ผ่อน 0% และเครดิตเงินคืน ปรับสิทธิ์ได้ตามไลฟ์สไตล์", minSalary: 15000, categories: ["lowincome", "installment", "cashback"] },
    { title: "บัตรเครดิต SCB Beyond / Platinum", summary: "บัตรระดับบน สิทธิ์เลานจ์สนามบิน ร้านอาหาร และท่องเที่ยว", minSalary: 50000, categories: ["lounge", "travel", "dining"] },
    { title: "บัตรเครดิต SCB PRIME", summary: "บัตรสำหรับลูกค้า SCB PRIME สิทธิ์เลานจ์และเดินทาง", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
    { title: "บัตรเครดิต SCB FIRST", summary: "บัตรพรีเมียมสูงสุดสำหรับลูกค้า Wealth สิทธิ์เลานจ์ระดับสูง", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
  ],
  krungsri: [
    { title: "บัตรเครดิตกรุงศรี วีซ่า/มาสเตอร์การ์ด", summary: "บัตรเริ่มต้นใช้จ่ายทั่วไป สะสมคะแนนกรุงศรี", minSalary: 15000, categories: ["lowincome", "points", "cashback"] },
    { title: "บัตรเครดิตกรุงศรี แพลทินัม", summary: "สะสมคะแนนและสิทธิ์ผ่อน 0% ที่ร้านค้าร่วมรายการ", minSalary: 15000, categories: ["lowincome", "points", "installment"] },
    { title: "บัตรเครดิตกรุงศรี เลดี้ ไทเทเนียม", summary: "บัตรสำหรับผู้หญิง สิทธิ์ร้านอาหาร ความงาม และช้อปปิ้ง", minSalary: 15000, categories: ["lowincome", "dining", "points"] },
    { title: "บัตรเครดิตกรุงศรี นาว แพลทินัม (NOW)", summary: "เครดิตเงินคืนสายกิน ช้อปออนไลน์ และความบันเทิง", minSalary: 15000, categories: ["lowincome", "dining", "online", "cashback"] },
    { title: "บัตรเครดิตกรุงศรี เจซีบี แพลทินัม", summary: "สิทธิ์พิเศษที่ญี่ปุ่นและร้านค้า JCB ทั่วโลก สะสมคะแนน", minSalary: 15000, categories: ["lowincome", "travel", "points"] },
    { title: "บัตรเครดิตกรุงศรี ซิกเนเจอร์", summary: "บัตรระดับบน สิทธิ์เลานจ์สนามบิน ท่องเที่ยว และสะสมคะแนน", minSalary: 70000, categories: ["lounge", "travel", "dining", "points"] },
    { title: "บัตรเครดิตกรุงศรี เอ็กซ์คลูซีฟ ซิกเนเจอร์", summary: "บัตรพรีเมียม (Invitation) สิทธิ์เลานจ์และไลฟ์สไตล์ระดับสูงสุด", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
    { title: "บัตรเครดิตกรุงศรี แมนเชสเตอร์ ยูไนเต็ด", summary: "บัตรสำหรับแฟนบอลแมนยู สะสมคะแนนและสิทธิ์พิเศษ", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรกรุงศรีเฟิร์สช้อยส์ วีซ่า", summary: "เด่นผ่อน 0% นานและแบ่งจ่ายรายเดือน รับเครดิตเงินคืน", minSalary: 15000, categories: ["lowincome", "installment", "cashback"] },
  ],
  ktc: [
    { title: "บัตรเครดิต KTC VISA/Mastercard Classic", summary: "บัตรเริ่มต้น สะสมคะแนน KTC FOREVER ฟรีค่าธรรมเนียมตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "points"] },
    { title: "บัตรเครดิต KTC CASH BACK PLATINUM", summary: "เครดิตเงินคืนทุกการใช้จ่าย ฟรีค่าธรรมเนียมตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "cashback"] },
    { title: "บัตรเครดิต KTC VISA PLATINUM", summary: "บัตรแพลทินัมสะสมคะแนน สิทธิ์ผ่อน 0% ฟรีค่าธรรมเนียมตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "points", "installment"] },
    { title: "บัตรเครดิต KTC X Visa Signature", summary: "สายเที่ยวและช้อปออนไลน์ คะแนนคุ้ม ฟรีค่าธรรมเนียมตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "travel", "online", "points"] },
    { title: "บัตรเครดิต KTC JCB PLATINUM", summary: "สิทธิ์พิเศษที่ญี่ปุ่นและร้าน JCB ฟรีค่าธรรมเนียมตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "travel", "points"] },
    { title: "บัตรเครดิต KTC - Bangchak", summary: "เครดิตเงินคืนเมื่อเติมน้ำมันบางจาก ฟรีค่าธรรมเนียมตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "fuel", "cashback"] },
    { title: "บัตรเครดิต KTC PROUD", summary: "บัตรผ่อนสินค้าและกดเงินสด แบ่งจ่ายสบาย ฟรีค่าธรรมเนียมตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "installment"] },
    { title: "บัตรเครดิต KTC ROYAL ORCHID PLUS", summary: "สะสมไมล์การบินไทย ฟรีค่าธรรมเนียมตลอดชีพ เหมาะกับนักเดินทาง", minSalary: 50000, categories: ["nofee", "miles", "travel"] },
    { title: "บัตรเครดิต KTC VISA SIGNATURE", summary: "บัตรระดับบน สิทธิ์เลานจ์สนามบิน ร้านอาหาร และท่องเที่ยว", minSalary: 50000, categories: ["nofee", "lounge", "travel", "dining", "points"] },
    { title: "KTC X BANGKOK AIRWAYS VISA SIGNATURE", summary: "Blue Ribbon Club Lounge เฉพาะสนามบินสมุย 4 ครั้ง/ปี · สะสมไมล์ FlyerBonus 1.5:1 · ส่วนลด 15% แลกตั๋วบางกอกแอร์เวย์ส · ค่าธรรมเนียมรายปี 5,000 บาท (ฟรีเมื่อใช้จ่าย ≥600,000/ปี)", minSalary: 50000, categories: ["lounge", "travel", "miles"], url: "https://www.ktc.co.th/credit-card/co-branded/ktc-x-bangkok-airways-visa-signature" },
    { title: "KTC – BANGKOK AIRWAYS PLATINUM MASTERCARD", summary: "ฟรีค่าธรรมเนียมตลอดชีพ · สะสมไมล์ FlyerBonus 1.5:1 · ส่วนลด 15% แลกตั๋ว + 10% in-flight · ส่วนลดร้านอาหาร Culinary Collective (บัตรนี้ไม่มีสิทธิ์เลานจ์สนามบิน)", minSalary: 15000, categories: ["lowincome", "nofee", "miles", "travel", "dining"], url: "https://www.ktc.co.th/credit-card/co-branded/ktc-bangkok-airways-platinum-mastercard" },
    { title: "KTC PLATINUM MASTERCARD", summary: "ฟรีค่าธรรมเนียมตลอดชีพ · ส่วนลดร้านอาหาร Culinary Collective สูงสุด 10% · ผ่อน 0% สูงสุด 10 เดือน · ประกันเดินทาง 8 ลบ.", minSalary: 15000, categories: ["lowincome", "nofee", "points", "dining", "installment"] },
    { title: "KTC DIGITAL PLATINUM (VISA)", summary: "บัตรดิจิทัล Dynamic CVV · ฟรีตลอดชีพ · ประกันเดินทาง 8 ลบ. + ประกัน ตปท. 10 วัน · ผ่อน 0% สูงสุด 10 เดือน", minSalary: 15000, categories: ["lowincome", "nofee", "points", "travel", "installment"] },
    { title: "KTC UNIONPAY PLATINUM", summary: "ฟรีตลอดชีพ · ส่วนลด U Collection · คะแนน x2 ฮ่องกง/มาเก๊า/ไต้หวัน · ผ่อน 0% สูงสุด 10 เดือน", minSalary: 15000, categories: ["lowincome", "nofee", "points", "dining", "installment"] },
    { title: "KTC - BANGKOK AIRWAYS JCB PLATINUM", summary: "JCB Airport Lounge ตปท. + JCB Plaza · สะสมไมล์ FlyerBonus 1.5:1 + ลด 15% แลกตั๋ว · ฟรีตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "lounge", "miles", "travel", "points"], url: "https://www.ktc.co.th/credit-card/co-branded" },
  ],
  bbl: [
    { title: "บัตรเครดิตแพลทินัม ธนาคารกรุงเทพ", summary: "บัตรหลักสะสมคะแนน Thank You Rewards ใช้จ่ายทั่วไป", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิตไทเทเนียม ธนาคารกรุงเทพ", summary: "บัตรเริ่มต้นสำหรับช้อปปิ้งและใช้จ่ายประจำวัน สะสมคะแนน", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิตแอร์เอเชีย ธนาคารกรุงเทพ", summary: "สะสมคะแนน BIG Points แลกตั๋วบินแอร์เอเชีย", minSalary: 15000, categories: ["lowincome", "miles", "travel"] },
    { title: "บัตรเครดิตวีซ่า ซิกเนเจอร์ ธนาคารกรุงเทพ", summary: "บัตรระดับบน สิทธิ์เลานจ์สนามบิน ร้านอาหารและท่องเที่ยว", minSalary: 50000, categories: ["lounge", "travel", "dining"] },
    { title: "บัตรเครดิตแพลทินัม ลีดเดอร์ชิป ธนาคารกรุงเทพ", summary: "สิทธิ์พิเศษสำหรับลูกค้าองค์กรและผู้บริหาร สะสมคะแนน", minSalary: 50000, categories: ["points", "travel"] },
    { title: "บัตรอินฟินิท ธนาคารกรุงเทพ (Visa Infinite)", summary: "บัตรพรีเมียมสูงสุด สิทธิ์เลานจ์และบริการระดับโลก", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
    { title: "บัตรเครดิตกรุงเทพ อเมริกัน เอ็กซ์เพรส (Amex)", summary: "บัตร American Express จากธนาคารกรุงเทพ สะสมคะแนนและสิทธิพิเศษ Amex Selects", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิตกรุงเทพ M LIVE Visa Platinum", summary: "สายไลฟ์สไตล์/ความบันเทิง สะสมคะแนนและส่วนลดร้านอาหาร", minSalary: 15000, categories: ["lowincome", "points", "dining"] },
    { title: "บัตรเครดิตกรุงเทพแรบบิท (Rabbit)", summary: "ผูกบัตรแรบบิทขึ้น BTS และใช้จ่ายออนไลน์สะดวก", minSalary: 15000, categories: ["lowincome", "online"] },
    { title: "บัตรเครดิตกรุงเทพ ท่องเที่ยว แพลทินัม", summary: "บัตรสายเที่ยว ส่วนลดและสะสมคะแนนเพื่อการเดินทาง", minSalary: 15000, categories: ["lowincome", "travel", "points"] },
    { title: "บัตรเครดิตกรุงเทพ M LUXE Visa Signature", summary: "บัตรพรีเมียมระดับบนสุด สิทธิ์เลานจ์และไลฟ์สไตล์หรู", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
  ],
  ttb: [
    { title: "บัตรเครดิต ttb so smart", summary: "เครดิตเงินคืนทุกการใช้จ่าย ไม่ต้องลงทะเบียน", minSalary: 15000, categories: ["lowincome", "cashback"] },
    { title: "บัตรเครดิต ttb so fast", summary: "เน้นช้อปออนไลน์และผ่อน 0% รับเครดิตเงินคืนออนไลน์", minSalary: 15000, categories: ["lowincome", "online", "installment"] },
    { title: "บัตรเครดิต ttb so chill", summary: "เครดิตเงินคืนสายกิน เที่ยว และความบันเทิง", minSalary: 15000, categories: ["lowincome", "dining", "cashback", "travel"] },
    { title: "บัตรเครดิต ttb global house", summary: "ผ่อน 0% และส่วนลดที่โกลบอลเฮ้าส์", minSalary: 15000, categories: ["lowincome", "installment"] },
    { title: "บัตรเครดิต ttb royal orchid plus", summary: "สะสมไมล์การบินไทยทุกการใช้จ่าย", minSalary: 15000, categories: ["lowincome", "miles", "travel"] },
    { title: "บัตรเครดิต ttb absolute", summary: "บัตรระดับบน สิทธิ์เลานจ์สนามบินและท่องเที่ยว", minSalary: 75000, categories: ["lounge", "travel", "points"] },
    { title: "บัตรเครดิต ttb reserve signature", summary: "บัตรพรีเมียมสูงสุด สิทธิ์เลานจ์และบริการระดับสูง", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
  ],
  uob: [
    { title: "บัตรเครดิต UOB ONE", summary: "เครดิตเงินคืนทุกการใช้จ่ายและสายกิน", minSalary: 15000, categories: ["lowincome", "cashback", "dining"] },
    { title: "บัตรเครดิต UOB YOLO Platinum", summary: "เครดิตเงินคืนสายกิน เที่ยว ช้อปออนไลน์ และความบันเทิง", minSalary: 15000, categories: ["lowincome", "dining", "travel", "online", "cashback"] },
    { title: "บัตรเครดิต UOB World", summary: "บัตรสายเที่ยวและไลฟ์สไตล์ สะสมคะแนนคุ้ม", minSalary: 15000, categories: ["lowincome", "travel", "dining", "points"] },
    { title: "บัตรเครดิต UOB Black", summary: "สะสมคะแนนสายกินและไลฟ์สไตล์ในเมือง", minSalary: 15000, categories: ["lowincome", "dining", "points"] },
    { title: "บัตรเครดิต UOB Preferred Platinum", summary: "สะสมคะแนน UNI$ ช้อปปิ้งและร้านค้าร่วมรายการ", minSalary: 15000, categories: ["lowincome", "points"] },
    { title: "บัตรเครดิต UOB Lady's", summary: "บัตรสำหรับผู้หญิง สิทธิ์ช้อปปิ้งและร้านอาหาร", minSalary: 15000, categories: ["lowincome", "dining", "points"] },
    { title: "บัตรเครดิต UOB PRIVIMILES", summary: "สะสมไมล์เดินทางรวดเร็ว สิทธิ์เลานจ์สนามบิน เหมาะกับนักเดินทาง", minSalary: 50000, categories: ["miles", "travel", "lounge"] },
    { title: "บัตรเครดิต UOB Premier", summary: "ห้องรับรองสนามบินในไทย 2 ครั้ง/ปี (แสดงบัตร+Boarding Pass, ≤2 ชม./ครั้ง) สะสมคะแนนพิเศษ", minSalary: 30000, categories: ["lounge", "travel", "points"], url: "https://www.uob.co.th/personal-en/credit-cards/shopping/uob-premier-credit-card.page" },
    { title: "บัตรเครดิต UOB Lady's Solitaire", summary: "บัตรผู้หญิงระดับบน สิทธิ์ท่องเที่ยวและร้านอาหาร", minSalary: 30000, categories: ["travel", "dining"] },
    { title: "บัตรเครดิต UOB Visa Infinite", summary: "บัตรพรีเมียมสูงสุด สิทธิ์เลานจ์และบริการระดับโลก", minSalary: 100000, categories: ["premium", "lounge", "travel"] },
    { title: "บัตรเครดิต UOB Simple", summary: "ฟรีค่าธรรมเนียมตลอดชีพ · ผ่อน 0% สูงสุด 10 เดือน (UOB i-Plan) · เงินคืนเดือนเกิดที่ Starbucks · ดูหนัง SF 1 ฟรี 1", minSalary: 15000, categories: ["lowincome", "nofee", "installment", "cashback"] },
    { title: "บัตรเครดิต UOB Royal Orchid Plus Preferred", summary: "สะสมไมล์การบินไทย (ROP) ทุกการใช้จ่าย เหมาะกับนักเดินทาง", minSalary: 50000, categories: ["miles", "travel"] },
    { title: "บัตรเครดิต Citi Rewards (UOB)", summary: "สะสมคะแนน Citi Rewards ไม่มีวันหมดอายุ เด่นช้อปปิ้ง/ห้าง (ปัจจุบัน UOB ออกบัตรให้)", minSalary: 15000, categories: ["lowincome", "points", "online"] },
    { title: "บัตรเครดิต Citi Cash Back (UOB)", summary: "เครดิตเงินคืนหมวดร้านอาหาร ประกัน และน้ำมัน (ปัจจุบัน UOB ออกบัตรให้)", minSalary: 15000, categories: ["lowincome", "cashback", "dining", "fuel"] },
    { title: "บัตรเครดิต Citi Premier (UOB)", summary: "สะสมคะแนนแลกไมล์ได้หลายสายการบิน เด่นท่องเที่ยว (ปัจจุบัน UOB ออกบัตรให้)", minSalary: 30000, categories: ["travel", "points", "miles"] },
    { title: "บัตรเครดิต Citi Prestige (UOB)", summary: "บัตรพรีเมียม สิทธิ์เลานจ์สนามบินไม่จำกัด + คืนที่พักคืนที่ 4 (ปัจจุบัน UOB ออกบัตรให้)", minSalary: 50000, categories: ["premium", "lounge", "travel"] },
  ],
  cardx: [
    { title: "CardX JCB PLATINUM", summary: "JCB Lounge ฟรี 8 ครั้ง/ปี (60+ แห่งทั่วโลก) · เงินคืน 3% ใช้จ่าย ตปท. (ญี่ปุ่น/เกาหลี/ฮ่องกง/สิงคโปร์/ไต้หวัน) · ฟรีตลอดชีพ", minSalary: 15000, categories: ["lowincome", "nofee", "lounge", "cashback", "travel", "points"], url: "https://www.cardx.co.th/products/credit-card" },
    { title: "CardX ULTRA PLATINUM", summary: "บัตรหลัก สะสมคะแนน X ผ่อน 0% และส่วนลดร้านค้า", minSalary: 15000, categories: ["lowincome", "points", "installment"] },
    { title: "CardX FAMILY PLUS", summary: "เครดิตเงินคืนสูงสุด 5% หมวดครอบครัว/ซูเปอร์มาร์เก็ต", minSalary: 15000, categories: ["lowincome", "cashback"] },
    { title: "CardX UP2ME", summary: "ผ่อน 0% และเครดิตเงินคืน ปรับสิทธิ์ตามไลฟ์สไตล์", minSalary: 15000, categories: ["lowincome", "installment", "cashback"] },
    { title: "CardX TOYOTA PLATINUM", summary: "บัตรร่วมโตโยต้า สิทธิ์บริการรถยนต์และเครดิตเงินคืน", minSalary: 15000, categories: ["lowincome", "cashback"] },
    { title: "CardX BEYOND", summary: "บัตรระดับบน สิทธิ์เลานจ์สนามบิน ร้านอาหาร และท่องเที่ยว", minSalary: 70000, categories: ["lounge", "travel", "dining", "points"] },
  ],
  aeon: [
    { title: "AEON UnionPay Platinum", summary: "Miracle Lounge สุวรรณภูมิ/ดอนเมือง 2 ครั้ง/ปี — ต้องรับบัตรกำนัลก่อน (ลูกค้าใหม่ใช้จ่าย ≥20,000/60 วัน หรือเดิม ≥120,000/ปี)", minSalary: 15000, categories: ["lowincome", "lounge", "travel"], url: "https://www.aeon.co.th/aeon/news-events/privileges-union-pay-platinum" },
    { title: "AEON Royal Orchid Plus JCB Platinum", summary: "ห้องรับรองการบินไทย 2 ครั้ง/ปี (สุวรรณภูมิ Orchid Access + เชียงใหม่ Royal Orchid Lounge) + JCB Airport Lounge ตปท. · ห้องรับรองอิออน 4 ครั้ง/เดือน · สะสมไมล์ ROP · เงินคืน 3% ตั๋วการบินไทย · ค่าธรรมเนียมรายปี 3,000 บาท (ฟรีเมื่อใช้จ่าย ≥300,000/ปี)", minSalary: 30000, categories: ["lounge", "travel", "miles", "dining"], url: "https://www.aeon.co.th/aeon/cards/aeon-rop-platinum-card" },
    { title: "AEON Classic Visa", summary: "บัตรเริ่มต้น สะสมคะแนน AEON Point ผ่อน 0% ที่ร้านร่วมรายการ", minSalary: 15000, categories: ["lowincome", "points", "installment"] },
    { title: "AEON Gold Visa", summary: "บัตรทอง สะสมคะแนนและสิทธิพิเศษเพิ่มจากบัตรคลาสสิก", minSalary: 20000, categories: ["points", "cashback"] },
    { title: "AEON Gold Mastercard", summary: "บัตรทอง Mastercard สะสมคะแนนและส่วนลดร้านค้า", minSalary: 20000, categories: ["points", "cashback"] },
    { title: "AEON Primo Digital", summary: "บัตรดิจิทัล สมัครง่าย เน้นช้อปออนไลน์และเครดิตเงินคืน", minSalary: 15000, categories: ["lowincome", "online", "cashback"] },
    { title: "AEON Nextgen Digital", summary: "บัตรดิจิทัลสำหรับคนรุ่นใหม่ ช้อปออนไลน์รับสิทธิ์พิเศษ", minSalary: 15000, categories: ["lowincome", "online", "cashback"] },
    { title: "AEON Royal Orchid Plus World Mastercard", summary: "สะสมไมล์การบินไทย (ROP) + สิทธิ์ห้องรับรองการบินไทย เหมาะกับนักเดินทาง (รายได้ขั้นต่ำ 30,000)", minSalary: 30000, categories: ["lounge", "travel", "miles"], url: "https://www.aeon.co.th/aeon/cards/aeon-rop-world-card" },
  ],
  icbc: [
    { title: "ICBC ANY Mastercard Platinum", summary: "บัตรกำนัล Miracle Lounge + DragonPass — บัตรระดับ Platinum (รายได้ขั้นต่ำ 15,000 สัญชาติไทย)", minSalary: 15000, categories: ["lowincome", "lounge", "travel"], url: "https://www.icbcthai.com/th/column/1035483406035103745.html" },
    { title: "ICBC Global Travel", summary: "บัตร 3 สกุลเงิน + บัตรกำนัล Miracle Lounge + DragonPass — เหมาะกับสายเที่ยวต่างประเทศ", minSalary: 15000, categories: ["lowincome", "lounge", "travel", "online"], url: "https://www.icbcthai.com/th/column/1438059017468788915.html" },
  ],
  amex: [
    { title: "American Express Green Card", summary: "บัตรชาร์จเริ่มต้นของ Amex สะสม Membership Rewards + สิทธิ์ Amex Selects (รายได้ขั้นต่ำโปรดตรวจกับ Amex)", minSalary: 30000, categories: ["points", "dining"], url: "https://www.americanexpress.com/th/en/charge-cards/american-express-green-card/" },
    { title: "American Express Gold Card", summary: "บัตรชาร์จระดับทอง สะสมคะแนน + สิทธิ์ร้านอาหาร/ท่องเที่ยว · รายได้ขั้นต่ำ 420,000 บาท/ปี (~35,000/เดือน)", minSalary: 35000, categories: ["points", "dining", "travel"], url: "https://www.americanexpress.com/th/en/campaigns/gold-charge-card/" },
    { title: "American Express Platinum Credit Card", summary: "บัตรเครดิตระดับบน สิทธิ์เลานจ์สนามบินและท่องเที่ยว · รายได้ขั้นต่ำ 500,000 บาท/ปี (~42,000/เดือน)", minSalary: 42000, categories: ["lounge", "travel", "dining", "points"], url: "https://www.americanexpress.com/th/en/credit-cards/thai-platinum-credit-card/" },
    { title: "The Platinum Card (American Express)", summary: "บัตรชาร์จพรีเมียมสูงสุด สิทธิ์เลานจ์ทั่วโลก (Priority Pass/Centurion) และบริการระดับสูง", minSalary: 100000, categories: ["premium", "lounge", "travel", "points"], url: "https://www.americanexpress.com/th/en/charge-cards/thai-platinum-card/" },
  ],
};
